[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
holo_presale = "AawKke79hDe8sa3Luheb7ckktrqAviH8n7M3Ugi5tQBy"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keys/owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
