[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
holo_presale = "8wREhkFJdobMnAT5NMwv33zuzW6UnvCbqUY63QwLkr86"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "keys/owner.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
